apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
spec:
  selector:
    matchLabels:
      app: foo
  replicas: 3
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: k8s-demo-app
        image: ghcr.io/allensallinger/k8s-demo-app:master
        env:
        - name: K8S_DEMO_APP_MESSAGE
          value: 'Standard Message'
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        ports:
        - name: http
          containerPort: 8080
